# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/maxigestion_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=us_maxigestion
spring.datasource.password=123456789
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Cloudinary Configuration
cloudinary.cloud-name=dh4zagcac
cloudinary.api-key=851223675226374
cloudinary.api-secret=WHQawwRpNNDJ2BwvbtSFrjTaCfo

# File upload configuration
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=wilmergruiz14@gmail.com
spring.mail.password=jnbj zhlf avbz snde
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# SERVER
# ===============================
server.port=${PORT:8080}